# Stage 1: Builder
FROM node:24-alpine AS builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

# Stage 2: Runtime
FROM node:24-alpine

WORKDIR /app

COPY --from=builder /app .

RUN adduser -D appuser

USER appuser

CMD ["node", "app.js"]

